# Generated by Django 5.2.17 on 2026-09-07 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0004_etudiant_nom_parent_etudiant_whatsapp_parent'),
        ('paiements', '0002_add_classe_payment_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique de la bourse', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_utilisee', models.BooleanField(default=False)),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant_beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bourses', to='etudiants.etudiant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReductionEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reduction', models.CharField(choices=[('NONE', 'Aucune'), ('PERCENT_10', 'Réduction 10% (Formation)'), ('LIBRE_FORMATION', 'Réduction libre (Formation)'), ('LIBRE_INSCRIPTION', 'Réduction libre (Inscription)'), ('BOURSE', "Bourse d'études")], default='NONE', max_length=30)),
                ('target', models.CharField(default='FORMATION', max_length=20)),
                ('montant_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reductions', to='paiements.bourse')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reductions', to='etudiants.etudiant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
