# Generated by Django 5.2.8

from django.db import migrations, models


def backfill_validee(apps, schema_editor):
    """Les notes déjà existantes restent visibles : seules les nouvelles
    saisies seront soumises à la validation de l'administration."""
    Note = apps.get_model('notes', 'Note')
    Note.objects.filter(validee=False).update(validee=True)


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_unique_note_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='validee',
            field=models.BooleanField(default=False, help_text="Note visible par l'étudiant uniquement après validation par l'administration"),
        ),
        migrations.RunPython(backfill_validee, migrations.RunPython.noop),
    ]
