# Generated by Django 5.2.17 on 2026-09-07 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0016_preinscription_date_naissance_preinscriptiondocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('nom', models.CharField(max_length=200)),
                ('responsable_nom', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['filiere__nom', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='courseassignment',
            options={'ordering': ['cycle__ordre', 'niveau__nom', 'module__nom'], 'verbose_name': 'Attribution de Cours', 'verbose_name_plural': 'Attributions de Cours'},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Cycle', 'verbose_name_plural': 'Cycles'},
        ),
        migrations.RemoveConstraint(
            model_name='classe',
            name='unique_classe_per_filiere_niveau_annee',
        ),
        migrations.RemoveConstraint(
            model_name='courseassignment',
            name='unique_course_assignment_per_path',
        ),
        migrations.RemoveConstraint(
            model_name='cycle',
            name='unique_cycle_type_per_filiere',
        ),
        migrations.AlterField(
            model_name='classe',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academique.filiere'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='academique.filiere'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='academique.filiere'),
        ),
        migrations.AddField(
            model_name='specialite',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='academique.filiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academique.specialite'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='academique.specialite'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='academique.specialite'),
        ),
        migrations.AddConstraint(
            model_name='specialite',
            constraint=models.UniqueConstraint(fields=('filiere', 'nom'), name='unique_specialite_per_filiere'),
        ),
    ]
