# Generated by Django 5.2.17 on 2026-09-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0017_specialite_alter_courseassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscription',
            name='nom_parent2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom du second parent'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='relation_parent1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lien parent 1'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='relation_parent2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lien parent 2'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='whatsapp_parent2',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp du second parent'),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='nom_parent',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom du premier parent'),
        ),
        migrations.AlterField(
            model_name='preinscription',
            name='whatsapp_parent',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp du premier parent'),
        ),
    ]
