# Generated by Django 5.2.17 on 2026-09-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0018_preinscription_nom_parent2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscription',
            name='classe_souhaitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_inscriptions', to='academique.classe'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='specialite_souhaitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_inscriptions', to='academique.specialite'),
        ),
    ]
